server:
  port: 9090

spring:
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: esta_es_mi_compleja_clave_secreta

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: usuario-service
            uri: http://localhost:9091
            predicates:
              - Path=/usuarios/**

          - id: direccion-service
            uri: http://localhost:9092
            predicates:
              - Path=/direcciones/**

          - id: categoria-service
            uri: http://localhost:9093
            predicates:
              - Path=/categorias/**
          
          - id: producto-service
            uri: http://localhost:9094
            predicates:
              - Path=/productos/**
          
          - id: pedido-service
            uri: http://localhost:9095
            predicates:
              - Path=/pedidos/**
          
          - id: pedido-detalle-service
            uri: http://localhost:9096
            predicates:
              - Path=/pedido-detalles/**
          
          - id: envio-service
            uri: http://localhost:9097
            predicates:
              - Path=/envios/**
          
          - id: pago-service
            uri: http://localhost:9098
            predicates:
              - Path=/pagos/**
          
          - id: auth-service
            uri: http://localhost:9099
            predicates:
              - Path=/auth/**