spring.application.name=pago-service
server.port=9098

spring.datasource.url=jdbc:mysql://localhost:3306/bd_pago?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

api.base-url=http://localhost:9090
pedido.service.url=http://localhost:9095

logging.level.root=INFO
logging.level.com.pizzeria.pago_service=DEBUG
logging.file.name=logs/pago-service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.security.oauth2.resourceserver.jwt.secret-key=esta_es_mi_compleja_clave_secreta