spring.application.name=envio-service
server.port=9097

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/bd_envio?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Necesario para borrar la tabla y crearla nuevamente si reinicias el servicio o 
#si no caera el microservicio, por que se repite una condicion de logica  en el Dataloader.

#spring.jpa.hibernate.ddl-auto=create-drop

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
springdoc.swagger-ui.path=/envios/swagger-ui.html
# Permite que el microservicio reconozca que opera detrás de un proxy (Gateway)
server.forward-headers-strategy=framework



api.base-url=http://api-gateway:9090
pedido.service.url=http://pedido-service:9095

spring.security.oauth2.resourceserver.jwt.secret-key=esta_es_mi_compleja_clave_secreta