spring.application.name=direccion-service
server.port=9092

spring.datasource.url=jdbc:mysql://localhost:3306/bd_direccion?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

#revisar api.base-url para la conexion
api.base-url=http://localhost:9090 
usuario.service-url=http://localhost:9091

spring.security.oauth2.resourceserver.jwt.secret-key=esta_es_mi_compleja_clave_secreta