spring.application.name=direccion-service
server.port=9092

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/bd_direccion?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

#revisar api.base-url para la conexion
api.base-url=http://api-gateway:9090
usuario.service-url=http://usuario-service:9091

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
springdoc.swagger-ui.path=/direcciones/swagger-ui.html

# Permite que el microservicio reconozca que opera detrás de un proxy (Gateway)
server.forward-headers-strategy=framework



spring.security.oauth2.resourceserver.jwt.secret-key=esta_es_mi_compleja_clave_secreta